#!/usr/bin/env python3
"""Regenerate the two published schematic views using only Xschem and Sky130A."""
import argparse
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
TOP = "LELOTEMP_BIAS_IBP"
PORTS = "VDD_1V8 LPI IBP_1U<3> IBP_1U<2> IBP_1U<1> IBP_1U<0> LPO VD1 PWRUP_1V8 VSS PWRUP_N_1V8"


def generate(xschem, pdk_root, schematic, lvs, output):
    env = os.environ.copy()
    env["PDK_ROOT"] = str(pdk_root)
    with tempfile.TemporaryDirectory(prefix="bandgap-netlist-") as scratch:
        # scratch is generated by tempfile and contains no Tcl metacharacters.
        command = [xschem, "--rcfile", str(ROOT / "schematic/xschemrc"),
                   "-q", "-x", "-b", "-s", "--tcl",
                   f"set lvs_netlist {int(lvs)}; set netlist_dir {{{scratch}}}; set top_is_subckt 1;",
                   "-n", str(schematic)]
        run = subprocess.run(command, env=env, capture_output=True, text=True, timeout=60)
        log = run.stdout + run.stderr
        output.with_suffix(output.suffix + ".log").write_text(log)
        generated = Path(scratch) / (schematic.stem + ".spice")
        # Some Xschem builds return 10 after successful headless netlisting.
        if run.returncode not in (0, 10) or not generated.is_file():
            raise RuntimeError(f"Xschem failed ({run.returncode}); see {output}.log")
        text = generated.read_text()
        if re.search(r"IS MISSING|not found|could not|error", text + log, re.IGNORECASE):
            raise RuntimeError(f"Xschem reported an unresolved schematic or error; see {output}.log")
        if schematic.stem == TOP and f".subckt {TOP} {PORTS}" not in text:
            raise RuntimeError("Generated top port declaration differs from the published interface")
        text = text.replace(str(ROOT) + "/", "")
        text = "\n".join(line for line in text.splitlines() if line.strip().lower() != ".end") + "\n"
        output.write_text("* Standalone bandgap: generated from the bundled Xschem hierarchy.\n"
                          "* Pure schematic including LELOTEMP_OTAR; external Sky130 models loaded by bench.\n" + text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pdk-root", default=os.environ.get("PDK_ROOT"))
    parser.add_argument("--xschem", default="xschem")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "runs/netlist")
    args = parser.parse_args()
    if not args.pdk_root:
        parser.error("set PDK_ROOT or pass --pdk-root (the directory containing sky130A)")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for lvs, name in [(False, "bandgap.spice"), (True, "bandgap.lvs.spice")]:
        output = args.output_dir / name
        generate(args.xschem, Path(args.pdk_root), ROOT / "schematic/LELO_TEMP_SKY130A" / (TOP + ".sch"), lvs, output)
        print(output)


if __name__ == "__main__":
    main()
